/*
 * Copyright 2021 Utkrisht Chauhan
 */

/**
 *
 * @author Utkrisht
 */
public class CartFrame extends javax.swing.JFrame {

    /**
     * Creates new form CartFrame
     */
    Info i=new Info();
    Cart c=new Cart();
    public CartFrame() {
        initComponents();
    }
    
    public CartFrame(Info a,Cart b) {
        i=a;c=b;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mShirtLB = new javax.swing.JLabel();
        blazLB = new javax.swing.JLabel();
        trousLB = new javax.swing.JLabel();
        mShortLB = new javax.swing.JLabel();
        tShirtLB = new javax.swing.JLabel();
        casLB = new javax.swing.JLabel();
        mSportLB = new javax.swing.JLabel();
        mSlipLB = new javax.swing.JLabel();
        sneakLB = new javax.swing.JLabel();
        mShirtButton = new javax.swing.JButton();
        blazButton = new javax.swing.JButton();
        trousButton = new javax.swing.JButton();
        mShortButton = new javax.swing.JButton();
        tShirtButton = new javax.swing.JButton();
        casButton = new javax.swing.JButton();
        mSportButton = new javax.swing.JButton();
        mSlipButton = new javax.swing.JButton();
        sneakButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        wShirtLB = new javax.swing.JLabel();
        shirtB = new javax.swing.JButton();
        suitLB = new javax.swing.JLabel();
        suitB = new javax.swing.JButton();
        lahLB = new javax.swing.JLabel();
        lahB = new javax.swing.JButton();
        wShortLB = new javax.swing.JLabel();
        shortB = new javax.swing.JButton();
        topB = new javax.swing.JButton();
        topLB = new javax.swing.JLabel();
        heelB = new javax.swing.JButton();
        heelLB = new javax.swing.JLabel();
        wSportLB = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        sportB = new javax.swing.JButton();
        wSlipLB = new javax.swing.JLabel();
        slipB = new javax.swing.JButton();
        sanLB = new javax.swing.JLabel();
        sanB = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Shopping Portal");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Your cart");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Men's Fashion");

        mShirtLB.setForeground(new java.awt.Color(0, 0, 153));
        mShirtLB.setText("Shirt");

        blazLB.setForeground(new java.awt.Color(102, 0, 0));
        blazLB.setText("Blazer");

        trousLB.setForeground(new java.awt.Color(0, 102, 102));
        trousLB.setText("Trouser");

        mShortLB.setForeground(new java.awt.Color(0, 102, 102));
        mShortLB.setText("Shorts");

        tShirtLB.setForeground(new java.awt.Color(0, 204, 204));
        tShirtLB.setText("T-shirts");

        casLB.setForeground(new java.awt.Color(255, 51, 255));
        casLB.setText("Casual Shoes");

        mSportLB.setForeground(new java.awt.Color(153, 0, 153));
        mSportLB.setText("Sport shoes");

        mSlipLB.setForeground(new java.awt.Color(0, 51, 204));
        mSlipLB.setText("Slippers");

        sneakLB.setForeground(new java.awt.Color(255, 51, 51));
        sneakLB.setText("Sneakers");

        mShirtButton.setForeground(new java.awt.Color(0, 0, 153));
        mShirtButton.setText("Delete");
        mShirtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mShirtButtonActionPerformed(evt);
            }
        });

        blazButton.setForeground(new java.awt.Color(102, 0, 0));
        blazButton.setText("Delete");
        blazButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blazButtonActionPerformed(evt);
            }
        });

        trousButton.setForeground(new java.awt.Color(0, 102, 102));
        trousButton.setText("Delete");
        trousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trousButtonActionPerformed(evt);
            }
        });

        mShortButton.setForeground(new java.awt.Color(0, 102, 102));
        mShortButton.setText("Delete");
        mShortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mShortButtonActionPerformed(evt);
            }
        });

        tShirtButton.setForeground(new java.awt.Color(0, 204, 204));
        tShirtButton.setText("Delete");
        tShirtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tShirtButtonActionPerformed(evt);
            }
        });

        casButton.setForeground(new java.awt.Color(255, 51, 255));
        casButton.setText("Delete");
        casButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casButtonActionPerformed(evt);
            }
        });

        mSportButton.setForeground(new java.awt.Color(153, 0, 153));
        mSportButton.setText("Delete");
        mSportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSportButtonActionPerformed(evt);
            }
        });

        mSlipButton.setForeground(new java.awt.Color(0, 51, 204));
        mSlipButton.setText("Delete");
        mSlipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSlipButtonActionPerformed(evt);
            }
        });

        sneakButton.setForeground(new java.awt.Color(255, 51, 51));
        sneakButton.setText("Delete");
        sneakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sneakButtonActionPerformed(evt);
            }
        });

        wShirtLB.setForeground(new java.awt.Color(0, 0, 153));
        wShirtLB.setText("Shirt");

        shirtB.setForeground(new java.awt.Color(0, 0, 153));
        shirtB.setText("Delete");
        shirtB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shirtBActionPerformed(evt);
            }
        });

        suitLB.setForeground(new java.awt.Color(153, 0, 102));
        suitLB.setText("Suits");

        suitB.setForeground(new java.awt.Color(153, 0, 102));
        suitB.setText("Delete");
        suitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suitBActionPerformed(evt);
            }
        });

        lahLB.setForeground(new java.awt.Color(0, 102, 51));
        lahLB.setText("Lahnga");

        lahB.setForeground(new java.awt.Color(0, 102, 51));
        lahB.setText("Delete");
        lahB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lahBActionPerformed(evt);
            }
        });

        wShortLB.setForeground(new java.awt.Color(0, 102, 102));
        wShortLB.setText("Shorts");

        shortB.setForeground(new java.awt.Color(0, 102, 102));
        shortB.setText("Delete");
        shortB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shortBActionPerformed(evt);
            }
        });

        topB.setForeground(new java.awt.Color(102, 0, 0));
        topB.setText("Delete");
        topB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topBActionPerformed(evt);
            }
        });

        topLB.setForeground(new java.awt.Color(102, 0, 0));
        topLB.setText("Top");

        heelB.setForeground(new java.awt.Color(255, 51, 102));
        heelB.setText("Delete");
        heelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heelBActionPerformed(evt);
            }
        });

        heelLB.setForeground(new java.awt.Color(255, 51, 102));
        heelLB.setText("High Heels");

        wSportLB.setForeground(new java.awt.Color(204, 0, 102));
        wSportLB.setText("Sport Shoes");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Women's Fashion");

        sportB.setForeground(new java.awt.Color(204, 0, 102));
        sportB.setText("Delete");
        sportB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportBActionPerformed(evt);
            }
        });

        wSlipLB.setForeground(new java.awt.Color(102, 51, 255));
        wSlipLB.setText("Slippers");

        slipB.setForeground(new java.awt.Color(102, 51, 255));
        slipB.setText("Delete");
        slipB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slipBActionPerformed(evt);
            }
        });

        sanLB.setForeground(new java.awt.Color(204, 102, 0));
        sanLB.setText("Sandle");

        sanB.setForeground(new java.awt.Color(204, 102, 0));
        sanB.setText("Delete");
        sanB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sanBActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Men Fashion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Women Fashion");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setText("Proceed to Check Out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(blazLB)
                                        .addComponent(mShirtLB)
                                        .addComponent(trousLB))
                                    .addGap(106, 106, 106)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(mShirtButton)
                                        .addComponent(blazButton)
                                        .addComponent(trousButton))
                                    .addGap(96, 96, 96)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(mShortLB)
                                        .addComponent(tShirtLB)
                                        .addComponent(casLB))
                                    .addGap(106, 106, 106)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(casButton)
                                        .addComponent(tShirtButton)
                                        .addComponent(mShortButton))
                                    .addGap(96, 96, 96)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(sneakLB)
                                        .addComponent(mSlipLB)
                                        .addComponent(mSportLB))
                                    .addGap(106, 106, 106)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(mSportButton)
                                        .addComponent(mSlipButton)
                                        .addComponent(sneakButton)))
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(wShirtLB)
                                        .addComponent(lahLB)
                                        .addComponent(suitLB))
                                    .addGap(106, 106, 106)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(shirtB)
                                        .addComponent(suitB)
                                        .addComponent(lahB))
                                    .addGap(96, 96, 96)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(wShortLB)
                                        .addComponent(topLB)
                                        .addComponent(heelLB))
                                    .addGap(106, 106, 106)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(shortB)
                                        .addComponent(topB)
                                        .addComponent(heelB))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(wSportLB)
                                            .addGap(105, 105, 105))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(123, 123, 123)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(sanLB)
                                                .addComponent(wSlipLB))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(sportB)
                                        .addComponent(slipB)
                                        .addComponent(sanB)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton1)
                                        .addComponent(jLabel20))
                                    .addGap(112, 112, 112)
                                    .addComponent(jButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                                    .addComponent(jButton3)
                                    .addGap(75, 75, 75)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jLabel1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mSportLB)
                    .addComponent(mShirtLB)
                    .addComponent(mShortLB)
                    .addComponent(mShirtButton)
                    .addComponent(mShortButton)
                    .addComponent(mSportButton))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blazLB)
                    .addComponent(tShirtLB)
                    .addComponent(mSlipLB)
                    .addComponent(blazButton)
                    .addComponent(tShirtButton)
                    .addComponent(mSlipButton))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sneakLB)
                    .addComponent(trousLB)
                    .addComponent(casLB)
                    .addComponent(trousButton)
                    .addComponent(casButton)
                    .addComponent(sneakButton))
                .addGap(38, 38, 38)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shirtB)
                            .addComponent(shortB)
                            .addComponent(wShirtLB)
                            .addComponent(wShortLB))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(suitB)
                                    .addComponent(topB)
                                    .addComponent(suitLB))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lahB)
                                    .addComponent(heelB)
                                    .addComponent(lahLB)
                                    .addComponent(heelLB)))
                            .addComponent(topLB, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sportB)
                            .addComponent(wSportLB))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(slipB)
                            .addComponent(wSlipLB))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sanB)
                            .addComponent(sanLB))))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        jLabel2.setText(i.name+"'s cart");
        if(c.m.st==0) mShirtButton.doClick();
        if(c.m.bl==0) blazButton.doClick();
        if(c.m.tr==0) trousButton.doClick();
        if(c.m.sh==0) mShortButton.doClick();
        if(c.m.ts==0) tShirtButton.doClick();
        if(c.m.cs==0) casButton.doClick();
        if(c.m.ss==0) mSportButton.doClick();
        if(c.m.sl==0) mSlipButton.doClick();
        if(c.m.sn==0) sneakButton.doClick();
        if(c.w.st==0) shirtB.doClick();
        if(c.w.sut==0) suitB.doClick();
        if(c.w.lg==0) lahB.doClick();
        if(c.w.sh==0) shortB.doClick();
        if(c.w.tp==0) topB.doClick();
        if(c.w.hh==0) heelB.doClick();
        if(c.w.ss==0) sportB.doClick();
        if(c.w.sl==0) slipB.doClick();
        if(c.w.san==0) sanB.doClick();
    }//GEN-LAST:event_formWindowGainedFocus

    private void mShirtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mShirtButtonActionPerformed
        // TODO add your handling code here:
        mShirtLB.setVisible(false);
        c.m.st=0;
        mShirtButton.setVisible(false);
    }//GEN-LAST:event_mShirtButtonActionPerformed

    private void blazButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blazButtonActionPerformed
        // TODO add your handling code here:
        blazLB.setVisible(false);
        c.m.bl=0;
        blazButton.setVisible(false);
    }//GEN-LAST:event_blazButtonActionPerformed

    private void trousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trousButtonActionPerformed
        // TODO add your handling code here:
        trousLB.setVisible(false);
        c.m.tr=0;
        trousButton.setVisible(false);
    }//GEN-LAST:event_trousButtonActionPerformed

    private void mShortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mShortButtonActionPerformed
        // TODO add your handling code here:
        mShortLB.setVisible(false);
        c.m.sh=0;
        mShortButton.setVisible(false);
    }//GEN-LAST:event_mShortButtonActionPerformed

    private void tShirtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tShirtButtonActionPerformed
        // TODO add your handling code here:
        tShirtLB.setVisible(false);
        c.m.ts=0;
        tShirtButton.setVisible(false);
    }//GEN-LAST:event_tShirtButtonActionPerformed

    private void casButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casButtonActionPerformed
        // TODO add your handling code here:
        casLB.setVisible(false);
        c.m.cs=0;
        casButton.setVisible(false);
    }//GEN-LAST:event_casButtonActionPerformed

    private void mSportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSportButtonActionPerformed
        // TODO add your handling code here:
        mSportLB.setVisible(false);
        c.m.ss=0;
        mSportButton.setVisible(false);
    }//GEN-LAST:event_mSportButtonActionPerformed

    private void mSlipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSlipButtonActionPerformed
        // TODO add your handling code here:
        mSlipLB.setVisible(false);
        c.m.sl=0;
        mSlipButton.setVisible(false);
    }//GEN-LAST:event_mSlipButtonActionPerformed

    private void sneakButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sneakButtonActionPerformed
        // TODO add your handling code here:
        sneakLB.setVisible(false);
        c.m.sn=0;
        sneakButton.setVisible(false);
    }//GEN-LAST:event_sneakButtonActionPerformed

    private void shirtBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shirtBActionPerformed
        // TODO add your handling code here:
        wShirtLB.setVisible(false);
        c.w.st=0;
        shirtB.setVisible(false);
    }//GEN-LAST:event_shirtBActionPerformed

    private void suitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suitBActionPerformed
        // TODO add your handling code here:
        suitLB.setVisible(false);
        c.w.sut=0;
        suitB.setVisible(false);
    }//GEN-LAST:event_suitBActionPerformed

    private void lahBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lahBActionPerformed
        // TODO add your handling code here:
        lahLB.setVisible(false);
        c.w.lg=0;
        lahB.setVisible(false);
    }//GEN-LAST:event_lahBActionPerformed

    private void shortBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shortBActionPerformed
        // TODO add your handling code here:
        wShortLB.setVisible(false);
        c.w.sh=0;
        shortB.setVisible(false);
    }//GEN-LAST:event_shortBActionPerformed

    private void topBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topBActionPerformed
        // TODO add your handling code here:
        topLB.setVisible(false);
        c.w.tp=0;
        topB.setVisible(false);
    }//GEN-LAST:event_topBActionPerformed

    private void heelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heelBActionPerformed
        // TODO add your handling code here:
        heelLB.setVisible(false);
        c.w.hh=0;
        heelB.setVisible(false);
    }//GEN-LAST:event_heelBActionPerformed

    private void sportBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportBActionPerformed
        // TODO add your handling code here:
        wSportLB.setVisible(false);
        c.w.ss=0;
        sportB.setVisible(false);
    }//GEN-LAST:event_sportBActionPerformed

    private void slipBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slipBActionPerformed
        // TODO add your handling code here:
        wSlipLB.setVisible(false);
        c.w.sl=0;
        slipB.setVisible(false);
    }//GEN-LAST:event_slipBActionPerformed

    private void sanBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sanBActionPerformed
        // TODO add your handling code here:
        sanLB.setVisible(false);
        c.w.san=0;
        sanB.setVisible(false);
    }//GEN-LAST:event_sanBActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new Login(i,c).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Women(i,c).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Men(i,c).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CartFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blazButton;
    private javax.swing.JLabel blazLB;
    private javax.swing.JButton casButton;
    private javax.swing.JLabel casLB;
    private javax.swing.JButton heelB;
    private javax.swing.JLabel heelLB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton lahB;
    private javax.swing.JLabel lahLB;
    private javax.swing.JButton mShirtButton;
    private javax.swing.JLabel mShirtLB;
    private javax.swing.JButton mShortButton;
    private javax.swing.JLabel mShortLB;
    private javax.swing.JButton mSlipButton;
    private javax.swing.JLabel mSlipLB;
    private javax.swing.JButton mSportButton;
    private javax.swing.JLabel mSportLB;
    private javax.swing.JButton sanB;
    private javax.swing.JLabel sanLB;
    private javax.swing.JButton shirtB;
    private javax.swing.JButton shortB;
    private javax.swing.JButton slipB;
    private javax.swing.JButton sneakButton;
    private javax.swing.JLabel sneakLB;
    private javax.swing.JButton sportB;
    private javax.swing.JButton suitB;
    private javax.swing.JLabel suitLB;
    private javax.swing.JButton tShirtButton;
    private javax.swing.JLabel tShirtLB;
    private javax.swing.JButton topB;
    private javax.swing.JLabel topLB;
    private javax.swing.JButton trousButton;
    private javax.swing.JLabel trousLB;
    private javax.swing.JLabel wShirtLB;
    private javax.swing.JLabel wShortLB;
    private javax.swing.JLabel wSlipLB;
    private javax.swing.JLabel wSportLB;
    // End of variables declaration//GEN-END:variables
}
